# Basic workflow

name: CI

on:
  push:
    branches:
      - main

  # Allows to manually run fomr Actions tab
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js

        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: yarn install

      - name: Build And Test project
        run: yarn build

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1.9
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }} # Replace with your actual organization
          SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}   # Replace with your actual project key
        with:
          args: 
            -Dsonar.organization=${{ env.SONAR_ORGANIZATION }}
            -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }}
            -Dsonar.branch.name=${{ github.ref }}
            -X
